{
 "title": "Covid-19 US - States - SIR",
 "description": "Visualisation of Data from John Hopkins University of the Covid-19 Outbreak",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "States", "query": "SHOW TAG VALUES with KEY=state" },
   {
    "name": "County",
    "query": "SHOW TAG VALUES with KEY=county  WHERE \"state\" =~ /^$States$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "content": "<img src=\"https://github.com/xaviermerino/nomad-jobs/raw/master/demo-covid19/cadas.png\" height=\"100%\"></a>"
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select last(confirmed) as time, time as timestamp from covid19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 21, "x": 0, "y": 2 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"confirmed\") AS \"Confirmed\" FROM \"covid19\" WHERE (\"state\" =~ /^$States$/ AND \"county\" =~ /^$County$/) AND time > now() - 1d GROUP BY time(1d), \"geohash\", \"location\" fill(none)",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    },
    {
     "rawSql": "SELECT timestamp AS \"time\", geohash AS \"geohash\", confirmed AS \"Confirmed\", name AS \"location\" FROM bases\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Hospital Bed Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "targets": [
    { "target": "bed-usage", "type": "timeseries" }
   ]
  },
  {
   "title": "ICU Bed Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "targets": [
    { "target": "icu-usage", "type": "timeseries" }
   ]
  },
  {
   "title": "Ventilator Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "targets": [
    { "target": "ventilator-usage", "type": "timeseries" }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Doesnt filter as Population of world hard coded\n\nFuture Improvement to Store Country Populations",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"confirmed\")/sum(\"population\") FROM \"covid19\" WHERE (\"state\" =~ /^$States$/ AND \"county\" =~ /^$County$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"deaths\")/sum(\"population\") AS \"Death Rate\" FROM \"covid19\" WHERE (\"state\" =~ /^$States$/ AND \"county\" =~ /^$County$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "targets": [
    { "target": "Susceptible", "type": "timeseries" }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "targets": [
    { "target": "Infected", "type": "timeseries" }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "targets": [
    { "target": "Recovered", "type": "timeseries" }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "targets": [
    { "target": "R0", "type": "timeseries" }
   ]
  },
  {
   "title": "SIR Model",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Susceptible", "type": "timeseries" },
    { "target": "Infected", "type": "timeseries" },
    { "target": "Recovered", "type": "timeseries" }
   ]
  },
  {
   "title": "Resource Usage Model",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Hospitalization", "type": "timeseries" },
    { "target": "ICU", "type": "timeseries" },
    { "target": "Ventilator", "type": "timeseries" }
   ]
  },
  {
   "title": "Total Confirmed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "county" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "title": "New Confirmed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "county" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "county" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  },
  {
   "title": "New Deaths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "county" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$States$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$County$/" }
     ]
    }
   ]
  }
 ]
}