{
 "title": "Consul-Nomad-Dashboard",
 "time": { "from": "2020-04-01T21:27:01.589Z", "to": "2020-04-01T21:39:22.149Z" },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "consul_autopilot_healthy" }
   ]
  },
  {
   "title": "Last Leader Contact",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "targets": [
    { "expr": "consul_raft_leader_lastContact", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Elections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "targets": [
    { "expr": "consul_raft_state_candidate" }
   ]
  },
  {
   "title": "Leadership Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 0 },
   "targets": [
    { "expr": "consul_raft_state_leader" }
   ]
  },
  {
   "title": "Consul RPC Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count (log base 10)" }
   ],
   "targets": [
    { "expr": "consul_rpc_request", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Serf Messages Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "consul_serf_msgs_received_count"
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_apply" }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "consul_runtime_sys_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "consul_runtime_gc_pause_ns" }
   ]
  },
  {
   "title": "Allocated Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "consul_runtime_alloc_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}