{
 "title": "Nomad Only",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Allocated CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_cpu" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_memory" }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Dead Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "targets": [
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of Go Routines",
   "type": "graph",
   "description": "a general load pressure indicator",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_runtime_num_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_rpc_request", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Last Leader Contact",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "targets": [
    { "expr": "consul_raft_leader_lastContact", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Average Allocated CPU ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "nomad_client_host_memory_used", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}