# config file version
apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: covid19
  user: 
  url: http://localhost:8086
  jsonData:
    timeInterval: "15s"
  secureJsonData:
    password: 